import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { useNavigate } from 'react-router-dom';

import Spinner from '../components/Spinner';
import './createInventory.css';

const CreateInventory = () => {
  const [quantity, setQuantity] = useState('');
  const [loading, setLoading] = useState(false);
  const [quantityError, setQuantityError] = useState('');
  const [createdInventoryId, setCreatedInventoryId] = useState('');
  const [preGeneratedInventoryId, setPreGeneratedInventoryId] = useState('');
  const navigate = useNavigate();
  const quantityRef = useRef(null);

  useEffect(() => {
    // pre-generate inventory id in format INV-YYYYMMDD-HHMM using local time
    const pad = (n) => n.toString().padStart(2, '0');
    const now = new Date();
    const year = now.getFullYear();
    const month = pad(now.getMonth() + 1);
    const day = pad(now.getDate());
    const hours = pad(now.getHours());
    const minutes = pad(now.getMinutes());
    const generated = `INV-${year}${month}${day}-${hours}${minutes}`;
    setPreGeneratedInventoryId(generated);
  }, []);

  useEffect(() => {
    // focus the quantity input when modal finishes loading
    if (!loading) {
      setTimeout(() => {
        quantityRef.current?.focus();
      }, 0);
    }
  }, [loading]);

  const handleSaveInventory = () => {
    if (quantityError || !quantity) {
      toast.error('Please fill all fields correctly');
      return;
    }
    if (quantity <= 0) {
      toast.error('Quantity must be greater than 0');
      return;
    }
    const data = {
      quantity_kg: parseInt(quantity),
    };
    setLoading(true);

    // Get JWT token for manager authentication
    const token = localStorage.getItem('jwtToken');
    
    axios
      .post('/api/manager/inventory', data, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      })
      .then((response) => {
        setLoading(false);
        // Display the auto-generated inventory ID from backend
        if (response.data && response.data.data && response.data.data.inventoryid) {
          setCreatedInventoryId(response.data.data.inventoryid);
          toast.success(`Inventory created successfully! ID: ${response.data.data.inventoryid}`);
        } else {
          // fallback confirmation when server didn't return an id
          toast.success('Inventory created successfully!');
        }
         // Navigate after short delay so user can read the toast
            setTimeout(() => {
              // Navigate back to dashboard and force a reload so latest inventory data is fetched
              navigate('/production-manager-dashboard');
              // Use replace to avoid adding an extra history entry, then reload
              setTimeout(() => {
                try { window.location.replace('/production-manager-dashboard'); } catch (e) { window.location.href = '/production-manager-dashboard'; }
              }, 50);
            }, 600);
      })
      .catch((error) => {
        console.error('Error saving inventory:', error);
        toast.error('An error occurred while saving inventory');
        setLoading(false);
      });
  };

  useEffect(() => {
    // Real-time validation for quantity
    if (quantity.length > 6) {
      setQuantityError('Quantity must not exceed 6 digits');
    } else if (quantity && parseInt(quantity) <= 0) {
      setQuantityError('Quantity must be greater than 0');
    } else {
      setQuantityError('');
    }
  }, [quantity]);

  const handleQuantityChange = (e) => {
    const value = e.target.value;
    if (value.length <= 6) {
      setQuantity(value);
    }
  };

  return (
    <div className="ci-root">
      {/* Modal backdrop */}
      <div className="ci-backdrop" onClick={() => navigate('/production-manager-dashboard')}>
        <div className="ci-modal" onClick={(e) => e.stopPropagation()}>
          <h1 className="ci-title">Create Inventory</h1>

          {loading && <Spinner />}

          {!loading && (
            <div className="ci-form">
              <div className="ci-field">
                <label className="ci-label">Inventory Number</label>
                <input
                  type="text"
                  value={createdInventoryId || preGeneratedInventoryId || ''}
                  placeholder={createdInventoryId || preGeneratedInventoryId ? '' : 'Will be generated by server (INV-YYYYMMDD-HHMM)'}
                  disabled
                  className="ci-input"
                />
                <p className="ci-note">Inventory ID is auto-generated by the server.</p>
              </div>

              <div className="ci-field">
                <label className="ci-label">Quantity (kg)</label>
                <input
                  type="number"
                  ref={quantityRef}
                  value={quantity}
                  onChange={handleQuantityChange}
                  min="1"
                  max="999999"
                  placeholder="Enter quantity in kilograms"
                  className={`ci-input ${quantityError ? 'ci-input-error' : ''}`}
                />
                {quantityError && <div className="ci-error">{quantityError}</div>}
                <p className="ci-note">* Enter the quantity of raw leaves in kilograms (max 6 digits)</p>
              </div>

              <div className="ci-actions">
                <button 
                  className="ci-btn ci-btn-primary" 
                  onClick={handleSaveInventory}
                  disabled={loading || quantityError || !quantity}
                >
                  {loading ? 'Saving...' : 'Save Inventory'}
                </button>

                <button 
                  className="ci-btn ci-btn-cancel" 
                  onClick={() => navigate('/production-manager-dashboard')}
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CreateInventory;